version: '3.5'

networks:
    foodie-cassandra-network:
      driver: bridge

services:
  cassandra-node1:
    image: cassandra:latest
    networks:
        - foodie-cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
      - CASSANDRA_HOST=127.0.0.1
    ports:
        - "9042:9042"

  cassandra-node2:
    image: cassandra:latest
    networks:
        - foodie-cassandra-network
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=password123
      - CASSANDRA_HOST=127.0.0.1